set(
    SOURCE_LIST
    Patcher/Calling.h 
    Patcher/General.h 
    Patcher/Injecting.h 
    Patcher/Main.h 
    Patcher/Memory.h 
    Patcher/PluginPatcher.h 
    Patcher/Reversed.h 
    Patcher/Calling.cpp 
    Patcher/General.cpp 
    Patcher/Injecting.cpp 
    Patcher/Main.cpp 
    Patcher/Memory.cpp 
    Patcher/PluginPatcher.cpp 
    Patcher/Reversed.cpp 
    Patcher/Shared.hpp 
    Patcher/Assembly/Assembly.h 
    Patcher/Assembly/Registers.h 
    Patcher/Assembly/Assembly.cpp 
    Patcher/Detours/Detours.h 
    Patcher/Detours/Detours.cpp 
    Patcher/HookingList/HookingList.h 
    Patcher/HookingList/HookingList.cpp 
    Patcher/ProcessHook/ProcessHooking.h 
    Patcher/ProcessHook/ProcessMemory.h 
    Patcher/ProcessHook/ProcessHooking.cpp 
    Patcher/ProcessHook/ProcessMemory.cpp 
    Patcher/RawHooks/RawHook.h 
    Patcher/RawHooks/RawHookVariable.h 
    Patcher/RawHooks/TheRawHooks.h 
    Patcher/RawHooks/RawHook.cpp 
    Patcher/RawHooks/RawHookVariable.cpp 
    Patcher/RawHooks/TheRawHooks.cpp 
    Patcher/Utils/ScopedUnprotect.h 
    Patcher/Utils/ScopedUnprotect.cpp 
    Patcher/VersionMgr/VersionMgr.h 
    Patcher/VersionMgr/VersionMgr.cpp
)