set(
    SOURCE_LIST
    src/Calling.h 
    src/General.h 
    src/Injecting.h 
    src/Main.h 
    src/Memory.h 
    src/PluginPatcher.h 
    src/Reversed.h 
    src/Calling.cpp 
    src/General.cpp 
    src/Injecting.cpp 
    src/Main.cpp 
    src/Memory.cpp 
    src/PluginPatcher.cpp 
    src/Reversed.cpp 
    src/Shared.hpp 
    src/Assembly/Assembly.h 
    src/Assembly/Registers.h 
    src/Assembly/Assembly.cpp 
    src/Detours/Detours.h 
    src/Detours/Detours.cpp 
    src/HookingList/HookingList.h 
    src/HookingList/HookingList.cpp 
    src/ProcessHook/ProcessHooking.h 
    src/ProcessHook/ProcessMemory.h 
    src/ProcessHook/ProcessHooking.cpp 
    src/ProcessHook/ProcessMemory.cpp 
    src/RawHooks/RawHook.h 
    src/RawHooks/RawHookVariable.h 
    src/RawHooks/TheRawHooks.h 
    src/RawHooks/RawHook.cpp 
    src/RawHooks/RawHookVariable.cpp 
    src/RawHooks/TheRawHooks.cpp 
    src/Utils/ScopedUnprotect.h 
    src/Utils/ScopedUnprotect.cpp 
    src/VersionMgr/VersionMgr.h 
    src/VersionMgr/VersionMgr.cpp
)